<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>hbdpg2</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>HBDPG2</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>

    <ApplicationIcon>Properties/Icon.ico</ApplicationIcon>
    <Version>1.1.0-beta.2</Version>
    <FileVersion>1.1.0.1</FileVersion>
    <Authors>Piotr Kniaz</Authors>
    <Product>HBDPG-2</Product>
    <Description>Deterministic password generator</Description>
    <Copyright>Copyright © 2025-2026 Piotr Kniaz</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Properties/Icon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageReference Include="Terminal.Gui" Version="2.1.0" />
  </ItemGroup>

</Project>
